apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-grafana
  namespace: prometheus
spec:
  ingressClassName: nginx
  rules:
  - host: "grafana.192.168.1.100.nip.io"
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: prometheus-grafana
            port:
              number: 80
